# -*- coding: utf-8 -*-
"""Taller16Abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWVEsU44OaHEeTmpAwr23h5YySc_fjWu

# Taller 16 Abril

Nicolas Quezada mora

## 1. Mezcla de fertilizantes
"""

# MEZCLA DE FERTILIZANTES

from scipy.optimize import linprog

# --- DATOS DEL PROBLEMA ---
# x1 = toneladas de fertilizante F1
# x2 = toneladas de fertilizante F2
#
# Max Z = 180x1 + 220x2
# linprog minimiza, por eso usamos -Z
c = [-180, -220]

# --- RESTRICCIONES ---
# Compuesto A: 3x1 + 4x2 <= 120
# Compuesto B: 2x1 + 1x2 <= 80
# Compuesto C: 5x1 + 3x2 <= 150
A_ub = [
    [3, 4],
    [2, 1],
    [5, 3],
]
b_ub = [120, 80, 150]

# --- LIMITES DE LAS VARIABLES (x >= 0) ---
bounds = [(0, None), (0, None)]


print("=" * 48)
print("  MEZCLA DE FERTILIZANTES - SciPy")
print("=" * 48)
print(f"Estado: {resultado.message}")
print()
print("VARIABLES DE DECISION:")
print("x1 = toneladas de fertilizante F1")
print("x2 = toneladas de fertilizante F2")
print("FUNCION OBJETIVO:")
print("Max Z = 180x1 + 220x2")
print()
print("CLASIFICACION DEL MODELO:")
print("Tipo: lineal")
print("Variables: continuas")
print()

"""## 2. Produccion semanal de una fabrica"""

# PRODUCCION SEMANAL DE UNA FABRICA

import numpy as np

# --- DATOS DEL PROBLEMA ---
# S_n = numero de sillas producidas en la semana n
# M_n = numero de mesas producidas en la semana n
#
# S_(n+1) = 0.6*S_n + 0.2*M_n + 40
# M_(n+1) = 0.1*S_n + 0.5*M_n + 20

S0 = 200
M0 = 80

# --- MATRIZ DEL SISTEMA ---
A = np.array([
    [0.6, 0.2],
    [0.1, 0.5],
])
b = np.array([40, 20])
x0 = np.array([S0, M0])

# --- CALCULAR SEMANA 1 Y 2 ---
x1 = A @ x0 + b
x2 = A @ x1 + b

# --- EQUILIBRIO ---
# En equilibrio se cumple: x = A*x + b
# (I - A)x = b
equilibrio = np.linalg.solve(np.eye(2) - A, b)

print("=" * 52)
print("  PRODUCCION SEMANAL DE UNA FABRICA - NumPy")
print("=" * 52)
print("VARIABLES DEL MODELO:")
print("Variable independiente: n (numero de semana)")
print("Variables dependientes: S_n y M_n")
print()
print("CLASIFICACION DEL MODELO:")
print("Tipo: lineal")
print("Variables: discretas")
print()
print(f"Semana 0 -> Sillas = {x0[0]:.4f}, Mesas = {x0[1]:.4f}")
print(f"Semana 1 -> Sillas = {x1[0]:.4f}, Mesas = {x1[1]:.4f}")
print(f"Semana 2 -> Sillas = {x2[0]:.4f}, Mesas = {x2[1]:.4f}")
print()
print(f"Equilibrio en sillas: {equilibrio[0]:.4f}")
print(f"Equilibrio en mesas:  {equilibrio[1]:.4f}")
print("=" * 52)

# --- VERIFICACION DEL EQUILIBRIO ---
lado_derecho = A @ equilibrio + b
print("\nVERIFICACION:")
print(f"S* = {equilibrio[0]:.4f}  |  RHS = {lado_derecho[0]:.4f}")
print(f"M* = {equilibrio[1]:.4f}  |  RHS = {lado_derecho[1]:.4f}")

"""## 3. Epidemia en una ciudad - Modelo SIS"""

# EPIDEMIA EN UNA CIUDAD

import numpy as np

# --- DATOS DEL PROBLEMA ---
# I(t) = numero de infectados
# S(t) = numero de susceptibles
# Poblacion total: S(t) + I(t) = 10000
#
# dI/dt = beta*(10000 - I)*I - gamma*I

N = 10000
beta = 0.00003
gamma = 0.1
I0 = 50
S0 = N - I0

# --- FUNCION DEL MODELO ---
def dI_dt(I):
    return beta * (N - I) * I - gamma * I

# --- PUNTOS DE EQUILIBRIO ---
# 0 = I * (beta*(N - I) - gamma)
I_eq_1 = 0.0
I_eq_2 = N - (gamma / beta)

S_eq_1 = N - I_eq_1
S_eq_2 = N - I_eq_2

print("=" * 50)
print("  EPIDEMIA EN UNA CIUDAD - Modelo SIS")
print("=" * 50)
print("VARIABLES Y PARAMETROS:")
print("Variable de estado principal: I(t)")
print("Variable relacionada: S(t) = 10000 - I(t)")
print(f"beta  = {beta}")
print(f"gamma = {gamma}")
print()
print("CLASIFICACION DEL MODELO:")
print("Tipo: no lineal")
print("Tiempo: continuo")
print("Termino no lineal: beta*(10000 - I)*I")
print()
print(f"Condicion inicial: I(0) = {I0:.4f}")
print(f"Susceptibles iniciales: S(0) = {S0:.4f}")
print()
print("PUNTOS DE EQUILIBRIO:")
print(f"Equilibrio 1 -> I* = {I_eq_1:.4f}, S* = {S_eq_1:.4f}")
print(f"Equilibrio 2 -> I* = {I_eq_2:.4f}, S* = {S_eq_2:.4f}")
print("=" * 50)

# --- VERIFICACION ---
print("\nVERIFICACION:")
print(f"dI/dt en I* = {I_eq_1:.4f}: {dI_dt(I_eq_1):.8f}")
print(f"dI/dt en I* = {I_eq_2:.4f}: {dI_dt(I_eq_2):.8f}")
print()
print("INTERPRETACION:")
print("Equilibrio 1: no hay infectados, la enfermedad desaparece.")
print("Equilibrio 2: estado endemico, la enfermedad permanece en la ciudad.")

"""## 4. Modelo logistico de pesca"""

# MODELO LOGISTICO DE PESCA

import numpy as np

# --- DATOS DEL PROBLEMA ---
# P_n = poblacion de peces al final del año n
#
# P_(n+1) = P_n + r*P_n*(1 - P_n/K) - H

r = 0.4
K = 1000
H = 80
P0 = 400

# --- MODELO DISCRETO ---
def siguiente_poblacion(P):
    return P + r * P * (1 - P / K) - H

# --- CALCULAR P1 Y P2 ---
P1 = siguiente_poblacion(P0)
P2 = siguiente_poblacion(P1)

# --- PUNTOS DE EQUILIBRIO ---
# En equilibrio: P_(n+1) = P_n = P*
# r*P*(1 - P/K) - H = 0
coeficientes = [r / K, -r, H]
equilibrios = np.roots(coeficientes)
equilibrios = np.sort(np.real_if_close(equilibrios))

P_eq_1 = float(equilibrios[0])
P_eq_2 = float(equilibrios[1])

# --- ESTABILIDAD LOCAL ---
# F'(P) = 1 + r - 2rP/K
def derivada_modelo(P):
    return 1 + r - (2 * r * P / K)

der_eq_1 = derivada_modelo(P_eq_1)
der_eq_2 = derivada_modelo(P_eq_2)

estabilidad_1 = "estable" if abs(der_eq_1) < 1 else "inestable"
estabilidad_2 = "estable" if abs(der_eq_2) < 1 else "inestable"

print("=" * 50)
print("  MODELO LOGISTICO DE PESCA - NumPy")
print("=" * 50)
print("VARIABLES Y PARAMETROS:")
print("Variable: P_n")
print(f"r = {r}")
print(f"K = {K}")
print(f"H = {H}")
print()
print("CLASIFICACION DEL MODELO:")
print("Tipo: no lineal")
print("Tiempo: discreto")
print()
print(f"Poblacion inicial P0 = {P0:.4f}")
print(f"Poblacion al final del año 1: P1 = {P1:.4f}")
print(f"Poblacion al final del año 2: P2 = {P2:.4f}")
print()
print("PUNTOS DE EQUILIBRIO:")
print(f"Equilibrio 1: P* = {P_eq_1:.4f} ({estabilidad_1})")
print(f"Equilibrio 2: P* = {P_eq_2:.4f} ({estabilidad_2})")
print("=" * 50)

# --- VERIFICACION ---
print("\nVERIFICACION:")
print(f"F(P*) en {P_eq_1:.4f} = {siguiente_poblacion(P_eq_1):.4f}")
print(f"F(P*) en {P_eq_2:.4f} = {siguiente_poblacion(P_eq_2):.4f}")
print()
print("INTERPRETACION:")
print("Si la poblacion inicia por debajo del equilibrio inestable,")
print("la pesca domina y la poblacion tiende a colapsar.")
print("Si inicia por encima de ese umbral, tiende al equilibrio estable.")